-- ============================================================
-- 超市管理系统 · Oracle AUTO INCREMENT 触发器
-- 文件：11_auto_increment_triggers.sql
-- 为所有使用 IdType.AUTO 的表添加 BEFORE INSERT 触发器
-- ============================================================

-- USERS
CREATE OR REPLACE TRIGGER trg_users_bi
  BEFORE INSERT ON USERS
  FOR EACH ROW
  WHEN (NEW.user_id IS NULL)
BEGIN
  SELECT SEQ_USERS.NEXTVAL INTO :NEW.user_id FROM dual;
END;
/

-- ORDERS
CREATE OR REPLACE TRIGGER trg_orders_bi
  BEFORE INSERT ON ORDERS
  FOR EACH ROW
  WHEN (NEW.order_id IS NULL)
BEGIN
  SELECT SEQ_ORDERS.NEXTVAL INTO :NEW.order_id FROM dual;
END;
/

-- ORDER_ITEMS
CREATE OR REPLACE TRIGGER trg_order_items_bi
  BEFORE INSERT ON ORDER_ITEMS
  FOR EACH ROW
  WHEN (NEW.item_id IS NULL)
BEGIN
  SELECT SEQ_ORDER_ITEMS.NEXTVAL INTO :NEW.item_id FROM dual;
END;
/

-- PRODUCTS
CREATE OR REPLACE TRIGGER trg_products_bi
  BEFORE INSERT ON PRODUCTS
  FOR EACH ROW
  WHEN (NEW.product_id IS NULL)
BEGIN
  SELECT SEQ_PRODUCTS.NEXTVAL INTO :NEW.product_id FROM dual;
END;
/

-- ADMINS
CREATE OR REPLACE TRIGGER trg_admins_bi
  BEFORE INSERT ON ADMINS
  FOR EACH ROW
  WHEN (NEW.admin_id IS NULL)
BEGIN
  SELECT SEQ_ADMIN.NEXTVAL INTO :NEW.admin_id FROM dual;
END;
/

-- AFTER_SALES
CREATE OR REPLACE TRIGGER trg_after_sales_bi
  BEFORE INSERT ON AFTER_SALES
  FOR EACH ROW
  WHEN (NEW.as_id IS NULL)
BEGIN
  SELECT SEQ_AFTER_SALES.NEXTVAL INTO :NEW.as_id FROM dual;
END;
/

-- REVIEWS
CREATE OR REPLACE TRIGGER trg_reviews_bi
  BEFORE INSERT ON REVIEWS
  FOR EACH ROW
  WHEN (NEW.review_id IS NULL)
BEGIN
  SELECT SEQ_REVIEWS.NEXTVAL INTO :NEW.review_id FROM dual;
END;
/

-- COUPONS
CREATE OR REPLACE TRIGGER trg_coupons_bi
  BEFORE INSERT ON COUPONS
  FOR EACH ROW
  WHEN (NEW.coupon_id IS NULL)
BEGIN
  SELECT SEQ_COUPONS.NEXTVAL INTO :NEW.coupon_id FROM dual;
END;
/

-- USER_COUPONS
CREATE OR REPLACE TRIGGER trg_user_coupons_bi
  BEFORE INSERT ON USER_COUPONS
  FOR EACH ROW
  WHEN (NEW.uc_id IS NULL)
BEGIN
  SELECT SEQ_USER_COUPONS.NEXTVAL INTO :NEW.uc_id FROM dual;
END;
/

-- COURIERS
CREATE OR REPLACE TRIGGER trg_couriers_bi
  BEFORE INSERT ON COURIERS
  FOR EACH ROW
  WHEN (NEW.courier_id IS NULL)
BEGIN
  SELECT SEQ_COURIER.NEXTVAL INTO :NEW.courier_id FROM dual;
END;
/

-- DELIVERY_TASKS
CREATE OR REPLACE TRIGGER trg_delivery_tasks_bi
  BEFORE INSERT ON DELIVERY_TASKS
  FOR EACH ROW
  WHEN (NEW.task_id IS NULL)
BEGIN
  SELECT SEQ_DELIVERY_TASKS.NEXTVAL INTO :NEW.task_id FROM dual;
END;
/

-- BANNERS
CREATE OR REPLACE TRIGGER trg_banners_bi
  BEFORE INSERT ON BANNERS
  FOR EACH ROW
  WHEN (NEW.banner_id IS NULL)
BEGIN
  SELECT SEQ_BANNERS.NEXTVAL INTO :NEW.banner_id FROM dual;
END;
/

-- ADDRESSES
CREATE OR REPLACE TRIGGER trg_addresses_bi
  BEFORE INSERT ON ADDRESSES
  FOR EACH ROW
  WHEN (NEW.address_id IS NULL)
BEGIN
  SELECT SEQ_ADDRESSES.NEXTVAL INTO :NEW.address_id FROM dual;
END;
/

-- INVENTORY_LOGS
CREATE OR REPLACE TRIGGER trg_inv_logs_bi
  BEFORE INSERT ON INVENTORY_LOGS
  FOR EACH ROW
  WHEN (NEW.log_id IS NULL)
BEGIN
  SELECT SEQ_INVENTORY_LOGS.NEXTVAL INTO :NEW.log_id FROM dual;
END;
/

-- CART
CREATE OR REPLACE TRIGGER trg_cart_bi
  BEFORE INSERT ON CART
  FOR EACH ROW
  WHEN (NEW.cart_id IS NULL)
BEGIN
  SELECT SEQ_CART.NEXTVAL INTO :NEW.cart_id FROM dual;
END;
/

-- AUDIT_LOGS (可能为 AUDIT_LOG)
CREATE OR REPLACE TRIGGER trg_audit_logs_bi
  BEFORE INSERT ON AUDIT_LOGS
  FOR EACH ROW
  WHEN (NEW.log_id IS NULL)
BEGIN
  SELECT SEQ_AUDIT_LOGS.NEXTVAL INTO :NEW.log_id FROM dual;
END;
/

-- PURCHASE_ORDERS
CREATE OR REPLACE TRIGGER trg_purchase_orders_bi
  BEFORE INSERT ON PURCHASE_ORDERS
  FOR EACH ROW
  WHEN (NEW.po_id IS NULL)
BEGIN
  SELECT SEQ_PURCHASE_ORDERS.NEXTVAL INTO :NEW.po_id FROM dual;
END;
/

-- PURCHASE_ORDER_ITEMS
CREATE OR REPLACE TRIGGER trg_po_items_bi
  BEFORE INSERT ON PURCHASE_ORDER_ITEMS
  FOR EACH ROW
  WHEN (NEW.item_id IS NULL)
BEGIN
  SELECT SEQ_PO_ITEM.NEXTVAL INTO :NEW.item_id FROM dual;
END;
/

-- SUPPLIERS
CREATE OR REPLACE TRIGGER trg_suppliers_bi
  BEFORE INSERT ON SUPPLIERS
  FOR EACH ROW
  WHEN (NEW.supplier_id IS NULL)
BEGIN
  SELECT SEQ_SUPPLIERS.NEXTVAL INTO :NEW.supplier_id FROM dual;
END;
/

COMMIT;
