-- Token 黑名单表，用于禁用账号后让已有token失效
CREATE TABLE TOKEN_BLACKLIST (
    TOKEN VARCHAR2(512) PRIMARY KEY,
    USER_ID NUMBER(10),
    USER_TYPE VARCHAR2(20),  -- user/admin/courier
    BLACKLISTED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    EXPIRES_AT TIMESTAMP
);